--1. Find total customers by countries
select country, count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

--2. Find total customers by gender

select gender, count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;

--3. Find total products by category
select category	, count(product_id) as total_products
from gold.dim_products
group by category;

--4. What is the average costs in each category?

select category	, avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

--5. What is the total revenue generated for each category?

select d.category , sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as d
on f.product_key = d.product_key
group by d.category
order by total_revenue desc;

--6. Find total revenue is generated by each customer

select 
	d.customer_key,
	d.first_name,
	d.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customers as d
on f.customer_key = d.customer_key
group by 
	d.customer_key,
	d.first_name,
	d.last_name
order by total_revenue desc;

--7. What is the distribution of sold items across countries?

select 
c.country,
sum(s.quantity) as total_sold_items 
from gold.fact_sales as s
left join gold.dim_customers as c
on c.customer_key = s.customer_key
group by c.country
order by total_sold_items desc;
